nicole_or_kiko/home/urls.py
from django.conf.urls import url

from . import views

app_name = 'home'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^result/$', views.result, name='result'),
]

nicole_or_kiko/nicole_or_kiko/urls.py
from django.conf.urls import include
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^home/', include('home.urls')),
    url(r'^admin/', admin.site.urls),
]

nicole_or_kiko/classifier/models.py
from django.db import models

# Create your models here.


class LabelList(models.Model):
    pass

nicole_or_kiko/home/models.py
from django import forms
from django.db import models

# Create your models here.


class InputSentence(forms.Form):
    sentence = forms.CharField()

nicole_or_kiko/scrap_instagram/models.py
from django.db import models

# Create your models here.

nicole_or_kiko/home/views.py
import json
import os
import pickle
import platform
import random
import string

import MeCab

from sklearn.externals import joblib
from sklearn.utils import check_random_state

from lime.lime_text import LimeTextExplainer

from django.shortcuts import render
from nicole_or_kiko.settings import BASE_DIR
from nicole_or_kiko import logging
from home.models import InputSentence

logger = logging.get_logger(__name__)

try:
    # load classifier
    CLF = joblib.load(os.path.join(BASE_DIR, "classifier", "classifier.pkl"))

    # load label list
    with open(os.path.join(BASE_DIR, "classifier", "label_list.pkl"), "rb") as rf:
        LABEL_LIST = pickle.load(rf)

except FileNotFoundError as err:
    logger.error(err)

PLATFORM_SYSTEM = platform.system()


def index(request):

    sentence = InputSentence()

    downloaded_dir = os.path.join(BASE_DIR,
                                  "scrap_instagram",
                                  "static",
                                  "scrap_instagram",
                                  "downloaded")

    user_dir = os.listdir(downloaded_dir)

    user_image_list = []
    for user in user_dir:
        images = list(filter(lambda x: x.endswith(".jpg"),
                             os.listdir(os.path.join(downloaded_dir, user))))

        user_images = list(map(lambda x: "{}/{}".format(user, x), images))
        user_images = random.sample(user_images, 5)
        user_image_list.extend(user_images)

    # user_image_dict_list = [{"src": '{% static "scrap_image/downloaded/{}" %}'.format(img)}
    #                         for img in user_image_list]
    user_image_dict_list = []
    for img in user_image_list:
        user_image_dict_list.append({"src": "/static/home/img/scrap_instagram/downloaded/{}".format(img)})

    logger.info(user_image_dict_list)

    context = {
        "sentence": sentence,
        "slides": jsonize(user_image_dict_list)
    }
    return render(request, "home/index.html", context)


def result(request):

    sentence = request.POST["sentence"]

    pred = predict(sentence)[0]

    pred_proba = predict_proba(sentence)
    logger.info("Predict proba: {}".format(pred_proba))
    explainer = LimeTextExplainer(class_names=LABEL_LIST)
    exp_instance = explainer.explain_instance(wakati(sentence), CLF.predict_proba)

    exp_labels = exp_instance.available_labels()

    random_id = id_generator(size=15, random_state=check_random_state(114514))

    top_div = '''
    <div class="lime top_div" id="top_div{}"></div>
    '''.format(random_id)

    # 事後確率を表示
    predict_proba_js = """
    var pp_div = top_div.append('div').classed('lime predict_proba', true);
    var pp_svg = pp_div.append('svg').style('width', '100%%');
    var pp = new lime.PredictProba(pp_svg, {}, {});
    """.format(jsonize(LABEL_LIST),
               jsonize(list(exp_instance.predict_proba.astype(float))))

    predict_value_js = ""

    # 予測に寄与した単語を表示
    exp_js = """
    var exp_div;
    var exp = new lime.Explanation({});
    """.format(jsonize(LABEL_LIST))

    for label in exp_labels:
        exp = jsonize(exp_instance.as_list())
        exp_js += """
        exp_div = top_div.append('div').classed('lime explanation', true);
        exp.show({}, {}, exp_div);
        """.format(exp, label)

    raw_js = """
    var raw_div = top_div.append('div');
    """
    logger.info("LABEL_LIST: {}".format(LABEL_LIST))
    logger.info("exp_labels: {}".format(exp_labels))
    logger.info("exp_instance.local_exp: {}".format(exp_instance.local_exp))

    # センテンスに対するアテンションを可視化
    html_data = exp_instance.local_exp[exp_labels[0]]
    raw_js += exp_instance.domain_mapper.visualize_instance_html(
        html_data, exp_labels[0],
        "raw_div",
        "exp")

    context = {
        "sentence": sentence,
        "pred": LABEL_LIST[pred],
        "pred_proba": pred_proba[0, 0],
        "as_list": jsonize(exp_instance.as_list()),
        # "bundle_js": bundle_js,
        "top_div": top_div,
        "random_id": random_id,
        "predict_proba_js": predict_proba_js,
        "predict_value_js": predict_value_js,
        "exp_js": exp_js,
        "raw_js": raw_js,
    }

    return render(request, "home/result.html", context)


def wakati(sentence):

    if PLATFORM_SYSTEM == "Linux":
        neologd_path = "/usr/lib/mecab/dic/mecab-ipadic-neologd"
    elif PLATFORM_SYSTEM == "Darwin":
        neologd_path = "/usr/local/lib/mecab/dic/mecab-ipadic-neologd"
    else:
        raise ValueError("Doesn't support {}".format(PLATFORM_SYSTEM))

    mt = MeCab.Tagger("-Owakati -d {}".format(neologd_path))
    return mt.parse(sentence)


def predict(sentence):

    return CLF.predict([wakati(sentence)])


def predict_proba(sentence):

    return CLF.predict_proba([wakati(sentence)])


def id_generator(size=15, random_state=None):

    chars = list(string.ascii_uppercase + string.digits)
    return ''.join(random_state.choice(chars, size, replace=True))


def jsonize(x):
    return json.dumps(x, ensure_ascii=False)

nicole_or_kiko/scrap_instagram/views.py
from django.shortcuts import render

# Create your views here.

nicole_or_kiko/home/templates/home/index.html
{% load static %}
<!DOCTYPE html>
<html lang=ja>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=UTF8">
    <link rel="stylesheet" type="text/css" href="{% static 'home/css/normalize.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'home/css/style.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'home/js/vegas/vegas.min.css' %}">

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

    <link href="{% static 'home/css/bootstrap/bootstrap.min.css' %}" rel="stylesheet">
    <script src="{% static 'home/js/bootstrap/bootstrap.min.js' %}"></script>
    <script src="{% static 'home/js/vegas/vegas.min.js' %}"></script>

    <script>
     $(function() {
       $('body').vegas({ //背景画像でスライドショーしたい場所の設定
	 slides: {{ slides | safe }},
			 delay: 10000, //スライドまでの時間ををミリ秒単位で設定
			 timer: true, //タイマーバーの表示/非表示を切り替え
			 overlay: '{% static "home/img/12.png" %}', //オーバーレイする画像の設定
			 animation: 'random', //スライドのアニメーションを設定
			 transition: 'fade', //スライド間のエフェクトを設定
			 transitionDuration: 4000 //エフェクト時間をミリ秒単位で設定
       });
     });
    </script>

  </head>
  <body>
    <div id="wrapper">

      <div align="center" id="title">
	<img src="{% static 'home/img/iyatomilab.png' %}" class="titleImage"/>
      </div>

      <div id="contents">
	<h1>Nicole or Kiko</h1>
	<div class="formInputSentence">
	  <form action="{% url 'home:result' %}" method="post">
	    <div class="form-group">
	      <label for="inputSentence">Input sentence</label>
	      <input type="text" class="form-control" id="inputSentence" name="sentence" placeholder="Input sentence">
	      {% csrf_token %}
	    </div>
	    <button type="submit" class="btn btn-default">Submit</button>
	  </form>
	</div>
	<div>
	  <h2>For example</h2>
	  <ul class="list-group">
	    <li class="list-group-item"><a href="https://www.instagram.com/takizawakarenofficial">@takizawakarenofficial</a> まさか、忘れてる方はいないと思いますが...今日も堂々とみなさんにご褒美です✨ 夏のしつこい足の引っ張り方が気になりますが、それでも立ち向かいたいだろう秋にひと手間かけてあげるのが私たちなのでしょうか⁉️</li>
	    <li class="list-group-item"><a href="https://www.instagram.com/kanna399">@kanna399</a> 砂で作ったタージ・マハール見に行きましょう♪ナオミは怪しい人しか引っ掻かないんですが…↑このセリフは訛って言えなかったんです。笑怪しい人しか、の部分です毎日毎日訛ってると言われます皆さん8chでリスザルが見れますよぉぉおお</li>
	    <li class="list-group-item"><a href="https://www.instagram.com/darenogare.akemi">@darenogare.akemi</a> 今日着てたアウターはGRLだよ 私も昨日届いて早速使ってます 暖かいし可愛い❤️もう少しで発売だからチェックしてね</li>
	    <li class="list-group-item"><a href="https://www.instagram.com/toritori0123">@toritori0123</a> ViVi9月号☺️ #Amazon にて予約スタート❤ イメージモデルをさせていただいている@majesticlegon_official のお洋服…</li>
	    <li class="list-group-item"><a href="https://lineblog.me/uesaka_sumire/">@uesaka_sumire</a> 本日は京都で「京アニ＆Ｄｏファン感謝イベント」中二病でも恋がしたい！トークステージに参加してきました(*´∀｀*)お足元の悪い中、お越しくださった方々ありがとうございましたっ！そして久々の京都〜！</li>
	  </ul>
	  
	</div>
      </div>

      <div id="indexFooter" class="clearfix">
	<div class="frawp">
	  <div class="copyRight">
	    Copyright &copy; Intelligent information processing laboratory IYATOMI Lab. All rights reserved.
	  </div>
	</div>
      </div>
      
    </div>
    
  </body>
</html>

nicole_or_kiko/home/templates/home/result.html
{% load static %}
<!DOCTYPE html>
<html lang=ja>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=UTF8">

    <script src="{% static 'home/js/bundle.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'home/css/normalize.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'home/css/style.css' %}" />
  </head>

  <body>
    <div id="wrapper" class="resultWrapper">

      <div align="center" id="title">
	<img src="{% static 'home/img/iyatomilab.png' %}" />
      </div>

      <div id="contents">
	<h1>Results</h1>
	<h2>{{ sentence }}</h2>
	<p>You look similar to this instagramer; {{ pred }}</p>
	<p>{{ pred_proba }}</p>
	{{ top_div | safe }}
	<script type="text/javascript">
	 var top_div = d3.select('#top_div{{ random_id }}').classed('lime top_div', true);
	 {{ predict_proba_js | safe }}
	 {{ predict_value_js | safe }}
	 {{ exp_js | safe }}
	 {{ raw_js | safe }}
	</script>
	<a class="returnTop" href="{% url 'home:index' %}">Return to home</a>
      </div>



      <div id="resultFooter" class="clearfix">
	<div class="frawp">
	  <div class="copyRight">
	    Copyright &copy; Intelligent information processing laboratory IYATOMI Lab. All rights reserved.
	  </div>
	</div>
      </div>
    </div>
  </body>
</html>